sudo: false
language: node_js
node_js: stable # use nodejs v10 LTS
cache: npm

install: 
  - npm install

branches:
  only:
    - master # build master branch only
script:
  - hexo clean
  - hexo generate # generate static files


deploy:
  provider: pages
  skip-cleanup: true
  github-token: SqE1+iGItjhgYEn4bqjUX43j/a6NwPVqitt+XpieE+A
  keep-history: true
  on:
    branch: main
  local-dir: public